name: Canned Answer
description: Suggest a new canned answer for our support tools
title: "[Canned Answer]: "
labels: ["canned answer"]
body:
    - type: markdown
      attributes:
          value: |
              Thanks for taking the time to create a request for a canned answer, most of the time these will be implemented as is and some times our team will want to improve, so keep an eye on the issue afterwards.
    - type: textarea
      attributes:
          label: Description
          description: Please write a the whole canned response here, please use `{variable}` to insert variables.
          placeholder: |
              Hi {name},

              Thanks so much for reaching out, but we no longer Support our Legacy Views, you will need
              to update to the new Views for our team to be able to assist you.

              https://evnt.is/v1-removal

              Best regards,
      validations:
          required: true

    - type: dropdown
      id: existing
      attributes:
          label: Searched for duplicates.
          description:
            "You can do this by searching [open requests](https://github.com/the-events-calendar/tampermonkey-scripts/issues) and [Existing canned answers](https://github.com/the-events-calendar/tampermonkey-scripts/tree/main/canned-answers)."
          options:
             - 'No'
             - 'Yes'
      validations:
          required: true

    - type: dropdown
      id: language-check
      attributes:
          label: Check Language
          description:
            "Please confirm that you checked the language of the Canned Response as it will be available and used by the whole company."
          options:
             - 'No'
             - 'Yes'
      validations:
          required: true
